services:
  atozgsm:
    build: .
    container_name: atozgsm
    restart: unless-stopped
    expose:
      - "8080"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.atozgsm.rule=Host(`atozgsm.com`) || Host(`www.atozgsm.com`)"
      - "traefik.http.routers.atozgsm.entrypoints=websecure"
      - "traefik.http.routers.atozgsm.tls.certresolver=letsencrypt"
      - "traefik.http.services.atozgsm.loadbalancer.server.port=8080"
